const express= require("express");
const { createStock, listStock, updateStock, deleteStock, deleteMultipleStocks, addnewStock, reportStock } = require("../Controller/StockController");
const router=express.Router();
router.post("/create", createStock);
router.get("/list", listStock);
router.put("/update/:id", updateStock);
router.put("/addnew/:id", addnewStock);
router.delete("/delete/:id", deleteStock);
router.delete("/deleteMultiple", deleteMultipleStocks);
router.get("/report", reportStock);
module.exports = router; 